package burp;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import net.portswigger.Zip;

class Zra6 extends HashMap<Zip, List<? extends Zvs>> {
  Zra6() {
    put(Zrrh.SCANNER_PASSIVE_CHECKS_HEADERS_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.BROWSER_XSS_FILTER_DISABLED, Zzu2.CLEARTEXT_SUBMISSION_OF_PASSWORD }));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_FORMS_DISABLED, Collections.emptyList());
    put(Zrrh.SCANNER_PASSIVE_CHECKS_LINKS_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.MIXED_CONTENT, Zzu2.SERIALIZED_OBJECT_IN_HTTP_MESSAGE, Zzu2.SESSION_TOKEN_IN_URL, Zzu2.CROSS_DOMAIN_SCRIPT_INCLUDE, Zzu2.CROSS_DOMAIN_REFERER_LEAKAGE, Zzu2.PATH_RELATIVE_STYLESHEET_IMPORT }));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_PARAMETERS_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.SESSION_TOKEN_IN_URL, Zzu2.BASE_64_ENCODED_DATA_IN_PARAMETER, Zzu2.SERIALIZED_OBJECT_IN_HTTP_MESSAGE, Zzu2.SQL_STATEMENT_IN_REQUEST_PARAMETER }));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_COOKIES_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.TLS_COOKIE_WITHOUT_SECURE_FLAG_SET, Zzu2.COOKIE_SCOPED_TO_PARENT_DOMAIN, Zzu2.DUPLICATE_COOKIES_SET, Zzu2.COOKIE_WITHOUT_HTTPONLY_FLAG }));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_SERVER_LEVEL_ISSUES_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.TLS_CERTIFICATE, Zzu2.UNENCRYPTED_COMMUNICATIONS, Zzu2.STRICT_TRANSPORT_SECURITY_NOT_ENFORCED, Zzu2.FLASH_CROSS_DOMAIN_POLICY, Zzu2.SILVERLIGHT_CROSS_DOMAIN_POLICY, Zzu2.CROSS_ORIGIN_RESOURCE_SHARING, Zzu2.CROSS_ORIGIN_RESOURCE_SHARING_UNTRUSTED_ORIGIN_TRUSTED, Zzu2.ROBOTS_TXT_FILE, Zzu2.ASP_NET_TRACING_ENABLED }));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_MIME_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.CONTENT_TYPE_NOT_SPECIFIED, Zzu2.HTML_DOES_NOT_SPECIFY_CHARSET, Zzu2.HTML_USES_UNRECOGNIZED_CHARSET, Zzu2.MULTIPLE_CONTENT_TYPES_SPECIFIED, Zzu2.CONTENT_TYPE_INCORRECTLY_STATED }));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_CACHING_DISABLED, Collections.singletonList(Zzu2.CACHEABLE_HTTPS_RESPONSE));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_INFORMATION_DISCLOSURE_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { 
            Zzu2.EMAIL_ADDRESSES_DISCLOSED, Zzu2.SOCIAL_SECURITY_NUMBERS_DISCLOSED, Zzu2.CREDIT_CARD_NUMBERS_DISCLOSED, Zzu2.DATABASE_CONNECTION_STRING_DISCLOSED, Zzu2.PRIVATE_KEY_DISCLOSED, Zzu2.SOURCE_CODE_DISCLOSURE, Zzu2.PASSWORD_RETURNED_IN_LATER_RESPONSE, Zzu2.PASSWORD_VALUE_SET_IN_COOKIE, Zzu2.PASSWORD_RETURNED_IN_URL_QUERY_STRING, Zzu2.PRIVATE_IP_ADDRESSES_DISCLOSED, 
            Zzu2.DIRECTORY_LISTING }));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_FRAMEABLE_RESPONSE_DISABLED, Collections.singletonList(Zzu2.FRAMEABLE_RESPONSE_POTENTIAL_CLICKJACKING));
    put(Zrrh.SCANNER_PASSIVE_CHECKS_DOT_NET_VIEWSTATE_DISABLED, Collections.singletonList(Zzu2.ASP_NET_VIEWSTATE_WITHOUT_MAC_ENABLED));
  }
}


/* Location:              C:\Program Files\BurpSuitePro\burpsuite_pro.jar!\burp\Zra6.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.1.3
 */