package burp;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import net.portswigger.Zip;

class Zznh extends HashMap<Zip, Collection<? extends Zvs>> {
  Zznh() {
    put(Zrrh.SCANNER_ACTIVE_CHECKS_SQL_INJECTION_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.SQL_INJECTION, Zzu2.SQL_INJECTION_2ND_ORDER }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_OS_COMMAND_INJECTION_DISABLED, Collections.singletonList(Zzu2.OS_COMMAND_INJECTION));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_SERVER_SIDE_CODE_INJECTION_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.PHP_CODE_INJECTION, Zzu2.PERL_CODE_INJECTION, Zzu2.PYTHON_CODE_INJECTION, Zzu2.RUBY_CODE_INJECTION, Zzu2.UNIDENTIFIED_CODE_INJECTION, Zzu2.SERVER_SIDE_JAVASCRIPT_CODE_INJECTION, Zzu2.SSI_INJECTION }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_SERVER_SIDE_TEMPLATE_INJECTION_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.SERVER_SIDE_TEMPLATE_ENGINE_INJECTION, Zzu2.EXPRESSION_LANGUAGE_ENGINE_INJECTION }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_REFLECTED_XSS_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.XSS_REFLECTED, Zzu2.CLIENT_SIDE_TEMPLATE_ENGINE_INJECTION }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_STORED_XSS_DISABLED, Collections.singletonList(Zzu2.XSS_STORED));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_REFLECTED_DOM_DISABLED, Ztai.Zl);
    put(Zrrh.SCANNER_ACTIVE_CHECKS_STORED_DOM_DISABLED, Ztai.ZD);
    put(Zrrh.SCANNER_ACTIVE_CHECKS_FILE_PATH_TRAVERSAL_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.FILE_PATH_MANIPULATION, Zzu2.FILE_PATH_TRAVERSAL }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_EXTERNAL_INTERACTION_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.EXTERNAL_SERVICE_INTERACTION_DNS, Zzu2.EXTERNAL_SERVICE_INTERACTION_HTTP, Zzu2.EXTERNAL_SERVICE_INTERACTION_SMTP }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_HEADER_INJECTION_DISABLED, Collections.singletonList(Zzu2.HTTP_RESPONSE_HEADER_INJECTION_REFLECTED));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_SMTP_INJECTION_DISABLED, Collections.singletonList(Zzu2.SMTP_HEADER_INJECTION));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_XML_INJECTION_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.XML_INJECTION, Zzu2.XML_ENTITY_EXPANSION, Zzu2.XML_EXTERNAL_ENTITY_INJECTION }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_LDAP_INJECTION_DISABLED, Collections.singletonList(Zzu2.LDAP_INJECTION));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_CSRF_DISABLED, Collections.singletonList(Zzu2.CROSS_SITE_REQUEST_FORGERY));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_OPEN_REDIRECTION_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.OPEN_REDIRECTION_REFLECTED, Zzu2.OPEN_REDIRECTION_STORED }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_HEADER_MANIPULATION_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.USER_AGENT_DEPENDENT_RESPONSE, Zzu2.SPOOFABLE_CLIENT_IP, Zzu2.REFERER_DEPENDENT_RESPONSE }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_SERVER_LEVEL_ISSUES_DISABLED, Arrays.asList((Zvs[])new Zzu2[] { Zzu2.TLS_CERTIFICATE, Zzu2.ROBOTS_TXT_FILE, Zzu2.CROSS_ORIGIN_RESOURCE_SHARING_ALL_SUBDOMAINS_TRUSTED, Zzu2.CROSS_ORIGIN_RESOURCE_SHARING_UNTRUSTED_ORIGIN_TRUSTED, Zzu2.CROSS_ORIGIN_RESOURCE_SHARING, Zzu2.CROSS_ORIGIN_RESOURCE_SHARING_ARBITRARY_ORIGIN, Zzu2.SILVERLIGHT_CROSS_DOMAIN_POLICY, Zzu2.FLASH_CROSS_DOMAIN_POLICY, Zzu2.ASP_NET_TRACING_ENABLED }));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_REFLECTED_INPUT_ENABLED, Collections.singletonList(Zzu2.INPUT_RETRIEVAL_REFLECTED));
    put(Zrrh.SCANNER_ACTIVE_CHECKS_STORED_INPUT_ENABLED, Collections.singletonList(Zzu2.INPUT_RETRIEVAL_STORED));
  }
}


/* Location:              C:\Program Files\BurpSuitePro\burpsuite_pro.jar!\burp\Zznh.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.1.3
 */